apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pythonappserver
  labels:
    env: production
    project: factors-production
data:
  ADWORDS_SERVER_PORT: "8091"
  ADWORDS_SERVER_PATH: "/usr/local/var/factors"
  CHAT_DATA_BUCKET: "factors-misc"

