apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pythonappserver
  labels:
    env: staging
    project: factors-staging
data:
  ADWORDS_SERVER_PORT: "8091"
  ADWORDS_SERVER_PATH: "/usr/local/var/factors"
  CHAT_DATA_BUCKET: "factors-staging-misc"
